sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7.4
      env:
        - EXECUTE_STATIC_ANALYSIS_CHECK=true
        - EXECUTE_BC_CHECK=true

before_install:
  - composer self-update --1
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer update --no-interaction

script:
  - make unit
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then make cs ; fi
  - if [[ $EXECUTE_STATIC_ANALYSIS_CHECK == 'true' ]]; then make static-analysis ; fi
  - if [[ $EXECUTE_BC_CHECK == 'true' ]]; then make bc-check ; fi
